[package]
name = "cli-datafusion"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
datafusion = "50"
tokio = { version = "1", features = ["rt-multi-thread"] }
